services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
    name: template-nest-nuxt_app
